app_name = "gifz-api"
region = "us-east-1"
environment = "production"
domain = "api.gifz.mkamycki.com"
app_domain = "gifz.mkamycki.com"
db_master_username = "postgres"
db_master_password = "test1234"
